insert into state VALUES (1, 'Saisie clôturée');
insert into state VALUES (2, 'Fiche créée, saisie en cours');
insert into state VALUES (3, 'Remboursée');
insert into state VALUES (4, 'Validée et mise en paiement');

insert into flate_rate_expense VALUES(1, 'Forfait Etape', 110.00);
insert into flate_rate_expense VALUES(2, 'Frais Kilométrique', 0.62);
insert into flate_rate_expense VALUES(3, 'Nuitée Hôtel', 80.00);
insert into flate_rate_expense VALUES(4, 'Repas Restaurant', 25.00);

insert into family values (1,'AA','Antalgiques en association');
insert into family values (2,'AAA','Antalgiques antipyrétiques en association');
insert into family values (3,'AAC','Antidépresseur d''action centrale');
insert into family values (4,'AAH','Antivertigineux antihistaminique H1');
insert into family values (5,'ABA','Antibiotique antituberculeux');
insert into family values (6,'ABC','Antibiotique antiacnéique local');
insert into family values (7,'ABP','Antibiotique de la famille des béta-lactamines (pénicilline A)');
insert into family values (8,'AFC','Antibiotique de la famille des cyclines');
insert into family values (9,'AFM','Antibiotique de la famille des macrolides');
insert into family values (10,'AH','Antihistaminique H1 local');
insert into family values (11,'AIM','Antidépresseur imipraminique (tricyclique)');
insert into family values (12,'AIN','Antidépresseur inhibiteur sélectif de la recapture de la sérotonine');
insert into family values (13,'ALO','Antibiotique local (ORL)');
insert into family values (14,'ANS','Antidépresseur IMAO non sélectif');
insert into family values (15,'AO','Antibiotique ophtalmique');
insert into family values (16,'AP','Antipsychotique normothymique');
insert into family values (17,'AUM','Antibiotique urinaire minute');
insert into family values (18,'CRT','Corticoïde antibiotique et antifongique à  usage local');
insert into family values (19,'HYP','Hypnotique antihistaminique');
insert into family values (20,'PSA','Psychostimulant antiasthénique');

insert into laboratory values (1,'BC', 'Bichat', 'Suzanne Terminus');
insert into laboratory values (2,'GY', 'Gyverny', 'Marcel MacDouglas');
insert into laboratory values (3,'SW', 'Swiss Kane', 'Alain Poutre');

insert into drug values (1, 18, '3MYC7', 'TRIMYCINE', 'Triamcinolone (acétonide) + Néomycine + Nystatine', 'Ce médicament est un corticoïde à  activité forte ou très forte associé à  un antibiotique et un antifongique, utilisé en application locale dans certaines atteintes cutanées surinfectées.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, d''infections de la peau ou de parasitisme non traités, d''acné. Ne pas appliquer sur une plaie, ni sous un pansement occlusif.','8,6');
insert into drug values (2, 7, 'ADIMOL9', 'ADIMOL', 'Amoxicilline + Acide clavulanique', 'Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.', 'Ce médicament est contre-indiqué en cas d''allergie aux pénicillines ou aux céphalosporines.','9,75');
insert into drug values (3, 7, 'AMOPIL7', 'AMOPIL', 'Amoxicilline', 'Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.', 'Ce médicament est contre-indiqué en cas d''allergie aux pénicillines. Il doit être administré avec prudence en cas d''allergie aux céphalosporines.','5,50');
insert into drug values (4, 7, 'AMOX45', 'AMOXAR', 'Amoxicilline', 'Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.', 'La prise de ce médicament peut rendre positifs les tests de dépistage du dopage.',null);
insert into drug values (5, 7, 'AMOXIG12', 'AMOXI Gé', 'Amoxicilline', 'Ce médicament, plus puissant que les pénicillines simples, est utilisé pour traiter des infections bactériennes spécifiques.', 'Ce médicament est contre-indiqué en cas d''allergie aux pénicillines. Il doit être administré avec prudence en cas d''allergie aux céphalosporines.','8,50');
insert into drug values (6, 13, 'APATOUX22', 'APATOUX Vitamine C', 'Tyrothricine + Tétracaïne + Acide ascorbique (Vitamine C)', 'Ce médicament est utilisé pour traiter les affections de la bouche et de la gorge.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, en cas de phénylcétonurie et chez l''enfant de moins de 6 ans.','5,250');
insert into drug values (7, 6, 'BACTIG10', 'BACTIGEL', 'Erythromycine', 'Ce médicament est utilisé en application locale pour traiter l''acné et les infections cutanées bactériennes associées.', 'Ce médicament est contre-indiqué en cas d''allergie aux antibiotiques de la famille des macrolides ou des lincosanides.','6,45');
insert into drug values (8, 9, 'BACTIV13', 'BACTIVIL', 'Erythromycine', 'Ce médicament est utilisé pour traiter des infections bactériennes spécifiques.', 'Ce médicament est contre-indiqué en cas d''allergie aux macrolides (dont le chef de file est l''érythromycine).','7,40');
insert into drug values (9, 2, 'BITALV', 'BIVALIC', 'Dextropropoxyphène + Paracétamol', 'Ce médicament est utilisé pour traiter les douleurs d''intensité modérée ou intense.', 'Ce médicament est contre-indiqué en cas d''allergie aux médicaments de cette famille, d''insuffisance hépatique ou d''insuffisance rénale.','4,70');
insert into drug values (10, 2, 'CARTION6', 'CARTION', 'Acide acétylsalicylique (aspirine) + Acide ascorbique (Vitamine C) + Paracétamol', 'Ce médicament est utilisé dans le traitement symptomatique de la douleur ou de la fièvre.', 'Ce médicament est contre-indiqué en cas de troubles de la coagulation (tendances aux hémorragies), d''ulcère gastroduodénal, maladies graves du foie.','7,00');
insert into drug values (11, 9, 'CLAZER6', 'CLAZER', 'Clarithromycine', 'Ce médicament est utilisé pour traiter des infections bactériennes spécifiques. Il est également utilisé dans le traitement de l''ulcère gastro-duodénal, en association avec d''autres médicaments.', 'Ce médicament est contre-indiqué en cas d''allergie aux macrolides (dont le chef de file est l''érythromycine).','2,45');
insert into drug values (12, 11, 'DEPRIL9', 'DEPRAMIL', 'Clomipramine', 'Ce médicament est utilisé pour traiter les épisodes dépressifs sévères, certaines douleurs rebelles, les troubles obsessionnels compulsifs et certaines énurésies chez l''enfant.', 'Ce médicament est contre-indiqué en cas de glaucome ou d''adénome de la prostate, d''infarctus récent, ou si vous avez reà§u un traitement par IMAO durant les 2 semaines précédentes ou en cas d''allergie aux antidépresseurs imipraminiques.','3,75');
insert into drug values (13, 3, 'DIMIRTAM6', 'DIMIRTAM', 'Mirtazapine', 'Ce médicament est utilisé pour traiter les épisodes dépressifs sévères.', 'La prise de ce produit est contre-indiquée en cas de d''allergie à  l''un des constituants.','5,62');
insert into drug values (14, 2, 'DOLRIL7', 'DOLORIL', 'Acide acétylsalicylique (aspirine) + Acide ascorbique (Vitamine C) + Paracétamol', 'Ce médicament est utilisé dans le traitement symptomatique de la douleur ou de la fièvre.', 'Ce médicament est contre-indiqué en cas d''allergie au paracétamol ou aux salicylates.','11,25');
insert into drug values (15, 19, 'DORNOM8', 'NORMADOR', 'Doxylamine', 'Ce médicament est utilisé pour traiter l''insomnie chez l''adulte.', 'Ce médicament est contre-indiqué en cas de glaucome, de certains troubles urinaires (rétention urinaire) et chez l''enfant de moins de 15 ans.','4,75');
insert into drug values (16, 4, 'EQUILARX6', 'EQUILAR', 'Méclozine', 'Ce médicament est utilisé pour traiter les vertiges et pour prévenir le mal des transports.', 'Ce médicament ne doit pas être utilisé en cas d''allergie au produit, en cas de glaucome ou de rétention urinaire.','7,42');
insert into drug values (17, 20, 'EVILR7', 'EVEILLOR', 'Adrafinil', 'Ce médicament est utilisé pour traiter les troubles de la vigilance et certains symptomes neurologiques chez le sujet agé.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants.','10,00');
insert into drug values (18, 10, 'INSXT5', 'INSECTIL', 'Diphénydramine', 'Ce médicament est utilisé en application locale sur les piqûres d''insecte et l''urticaire.', 'Ce médicament est contre-indiqué en cas d''allergie aux antihistaminiques.','5,45');
insert into drug values (19, 9, 'JOVAI8', 'JOVENIL', 'Josamycine', 'Ce médicament est utilisé pour traiter des infections bactériennes spécifiques.', 'Ce médicament est contre-indiqué en cas d''allergie aux macrolides (dont le chef de file est l''érythromycine).','7,20');
insert into drug values (20, 8, 'LIDOXY23', 'LIDOXYTRACINE', 'Oxytétracycline +Lidocaïne', 'Ce médicament est utilisé en injection intramusculaire pour traiter certaines infections spécifiques.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants. Il ne doit pas être associé aux rétinoïdes.','6,00');
insert into drug values (21, 16, 'LITHOR12', 'LITHORINE', 'Lithium', 'Ce médicament est indiqué dans la prévention des psychoses maniaco-dépressives ou pour traiter les états maniaques.', 'Ce médicament ne doit pas être utilisé si vous êtes allergique au lithium. Avant de prendre ce traitement, signalez à  votre médecin traitant si vous souffrez d''insuffisance rénale, ou si vous avez un régime sans sel.','8,10');
insert into drug values (22, 1, 'PARMOL16', 'PARMOCODEINE', 'Codéine + Paracétamol', 'Ce médicament est utilisé pour le traitement des douleurs lorsque des antalgiques simples ne sont pas assez efficaces.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, chez l''enfant de moins de 15 Kg, en cas d''insuffisance hépatique ou respiratoire, d''asthme, de phénylcétonurie et chez la femme qui allaite.','5,50');
insert into drug values (23, 20, 'PHYSOI8', 'PHYSICOR', 'Sulbutiamine', 'Ce médicament est utilisé pour traiter les baisses d''activité physique ou psychique, souvent dans un contexte de dépression.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants.','13,00');
insert into drug values (24, 5, 'PIRIZ8', 'PIRIZAN', 'Pyrazinamide', 'Ce médicament est utilisé, en association à  d''autres antibiotiques, pour traiter la tuberculose.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants, d''insuffisance rénale ou hépatique, d''hyperuricémie ou de porphyrie.','11,25');
insert into drug values (25, 15, 'POMDI20', 'POMADINE', 'Bacitracine', 'Ce médicament est utilisé pour traiter les infections oculaires de la surface de l''oeil.', 'Ce médicament est contre-indiqué en cas d''allergie aux antibiotiques appliqués localement.','9,75');
insert into drug values (26, 12, 'TROXT21', 'TROXADET', 'Paroxétine', 'Ce médicament est utilisé pour traiter la dépression et les troubles obsessionnels compulsifs. Il peut également être utilisé en prévention des crises de panique avec ou sans agoraphobie.', 'Ce médicament est contre-indiqué en cas d''allergie au produit.','4,12');
insert into drug values (27, 13, 'TXISOL22', 'TOUXISOL Vitamine C', 'Tyrothricine + Acide ascorbique (Vitamine C)', 'Ce médicament est utilisé pour traiter les affections de la bouche et de la gorge.', 'Ce médicament est contre-indiqué en cas d''allergie à  l''un des constituants et chez l''enfant de moins de 6 ans.','7,50');
insert into drug values (28, 17, 'URIEG6', 'URIREGUL', 'Fosfomycine trométamol', 'Ce médicament est utilisé pour traiter les infections urinaires simples chez la femme de moins de 65 ans.', 'La prise de ce médicament est contre-indiquée en cas d''allergie à  l''un des constituants et d''insuffisance rénale.','5,35');

insert into practitioner values (1,1, 'Notini', 'Alain', '114 r Authie', '85000', 'LA ROCHE SUR YON', '290,03');
insert into practitioner values (2,2, 'Gosselin', 'Albert', '13 r Devon', '41000', 'BLOIS', '307,49');
insert into practitioner values (3,5, 'Delahaye', 'André', '36 av 6 Juin', '25000', 'BESANCON', '185,79');
insert into practitioner values (4,3, 'Leroux', 'André', '47 av Robert Schuman', '60000', 'BEAUVAIS', '172,04');
insert into practitioner values (5,4, 'Desmoulins', 'Anne', '31 r St Jean', '30000', 'NIMES', '94,75');
insert into practitioner values (6,1, 'Mouel', 'Anne', '27 r Auvergne', '80000', 'AMIENS', '45,2');
insert into practitioner values (7,2, 'Desgranges-Lentz', 'Antoine', '1 r Albert de Mun', '29000', 'MORLAIX', '20,07');
insert into practitioner values (8,5, 'Marcouiller', 'Arnaud', '31 r St Jean', '68000', 'MULHOUSE', '396,52');
insert into practitioner values (9,3, 'Dupuy', 'Benoit', '9 r Demolombe', '34000', 'MONTPELLIER', '395,66');
insert into practitioner values (10,4, 'Lerat', 'Bernard', '31 r St Jean', '59000', 'LILLE', '257,79');
insert into practitioner values (11,1, 'Marçais-Lefebvre', 'Bertrand', '86Bis r Basse', '67000', 'STRASBOURG', '450,96');
insert into practitioner values (12,2, 'Boscher', 'Bruno', '94 r Falaise', '10000', 'TROYES', '356,14');
insert into practitioner values (13,5, 'Morel', 'Catherine', '21 r Chateaubriand', '75000', 'PARIS', '379,57');
insert into practitioner values (14,3, 'Guivarch', 'Chantal', '4 av Gén Laperrine', '45000', 'ORLEANS', '114,56');
insert into practitioner values (15,4, 'Bessin-Grosdoit', 'Christophe', '92 r Falaise', '06000', 'NICE', '222,06');
insert into practitioner values (16,1, 'Rossa', 'Claire', '14 av Thiès', '06000', 'NICE', '529,78');
insert into practitioner values (17,2, 'Cauchy', 'Denis', '5 av Ste Thérèse', '11000', 'NARBONNE', '458,82');
insert into practitioner values (18,5, 'Gaffé', 'Dominique', '9 av 1ère Armée Française', '35000', 'RENNES', '213,4');
insert into practitioner values (19,3, 'Guenon', 'Dominique', '98 bd Mar Lyautey', '44000', 'NANTES', '175,89');
insert into practitioner values (20,4, 'Prévot', 'Dominique', '29 r Lucien Nelle', '87000', 'LIMOGES', '151,36');
insert into practitioner values (21,1, 'Houchard', 'Eliane', '9 r Demolombe', '49100', 'ANGERS', '436,96');
insert into practitioner values (22,2, 'Desmons', 'Elisabeth', '51 r Bernières', '29000', 'QUIMPER', '281,17');
insert into practitioner values (23,5, 'Flament', 'Elisabeth', '11 r Pasteur', '35000', 'RENNES', '315,6');
insert into practitioner values (24,3, 'Goussard', 'Emmanuel', '9 r Demolombe', '41000', 'BLOIS', '40,72');
insert into practitioner values (25,4, 'Desprez', 'Eric', '9 r Vaucelles', '33000', 'BORDEAUX', '406,85');
insert into practitioner values (26,1, 'Coste', 'Evelyne', '29 r Lucien Nelle', '19000', 'TULLE', '441,87');
insert into practitioner values (27,2, 'Lefebvre', 'Frédéric', '2 pl Wurzburg', '55000', 'VERDUN', '573,63');
insert into practitioner values (28,5, 'Lemée', 'Frédéric', '29 av 6 Juin', '56000', 'VANNES', '326,4');
insert into practitioner values (29,3, 'Martin', 'Frédéric', 'Bât A 90 r Bayeux', '70000', 'VESOUL', '506,06');
insert into practitioner values (30,4, 'Marie', 'Frédérique', '172 r Caponière', '70000', 'VESOUL', '313,31');
insert into practitioner values (31,1, 'Rosenstech', 'Geneviève', '27 r Auvergne', '75000', 'PARIS', '366,82');
insert into practitioner values (32,2, 'Pontavice', 'Ghislaine', '8 r Gaillon', '86000', 'POITIERS', '265,58');
insert into practitioner values (33,5, 'Leveneur-Mosquet', 'Guillaume', '47 av Robert Schuman', '64000', 'PAU', '184,97');
insert into practitioner values (34,3, 'Blanchais', 'Guy', '30 r Authie', '08000', 'SEDAN', '502,48');
insert into practitioner values (35,4, 'Leveneur', 'Hugues', '7 pl St Gilles', '62000', 'ARRAS', '7,39');
insert into practitioner values (36,1, 'Mosquet', 'Isabelle', '22 r Jules Verne', '76000', 'ROUEN', '77,1');
insert into practitioner values (37,2, 'Giraudon', 'Jean-Christophe', '1 r Albert de Mun', '38100', 'VIENNE', '92,62');
insert into practitioner values (38,5, 'Marie', 'Jean-Claude', '26 r Hérouville', '69000', 'LYON', '120,1');
insert into practitioner values (39,3, 'Maury', 'Jean-François', '5 r Pierre Girard', '71000', 'CHALON SUR SAONE', '13,73');
insert into practitioner values (40,4, 'Dennel', 'Jean-Louis', '7 pl St Gilles', '28000', 'CHARTRES', '550,69');
insert into practitioner values (41,1, 'Ain', 'Jean-Pierre', '4 résid Olympia', '02000', 'LAON', '5,59');
insert into practitioner values (42,2, 'Chemery', 'Jean-Pierre', '51 pl Ancienne Boucherie', '14000', 'CAEN', '396,58');
insert into practitioner values (43,5, 'Comoz', 'Jean-Pierre', '35 r Auguste Lechesne', '18000', 'BOURGES', '340,35');
insert into practitioner values (44,3, 'Desfaudais', 'Jean-Pierre', '7 pl St Gilles', '29000', 'BREST', '71,76');
insert into practitioner values (45,4, 'Phan', 'JérÃ´me', '9 r Clos Caillet', '79000', 'NIORT', '451,61');
insert into practitioner values (46,1, 'Riou', 'Line', '43 bd Gén Vanier', '77000', 'MARNE LA VALLEE', '193,25');
insert into practitioner values (47,2, 'Chubilleau', 'Louis', '46 r Eglise', '17000', 'SAINTES', '202,07');
insert into practitioner values (48,5, 'Lebrun', 'Lucette', '178 r Auge', '54000', 'NANCY', '410,41');
insert into practitioner values (49,3, 'Goessens', 'Marc', '6 av 6 Juin', '39000', 'DOLE', '548,57');
insert into practitioner values (50,4, 'Laforge', 'Marc', '5 résid Prairie', '50000', 'SAINT LO', '265,05');
insert into practitioner values (51,1, 'Millereau', 'Marc', '36 av 6 Juin', '72000', 'LA FERTE BERNARD', '430,42');
insert into practitioner values (52,2, 'Dauverne', 'Marie-Christine', '69 av Charlemagne', '21000', 'DIJON', '281,05');
insert into practitioner values (53,5, 'Vittorio', 'Myriam', '3 pl Champlain', '94000', 'BOISSY SAINT LEGER', '356,23');
insert into practitioner values (54,3, 'Lapasset', 'Nhieu', '31 av 6 Juin', '52000', 'CHAUMONT', '107');
insert into practitioner values (55,4, 'Plantet-Besnier', 'Nicole', '10 av 1ère Armée Française', '86000', 'CHATELLEREAULT', '369,94');
insert into practitioner values (56,1, 'Chubilleau', 'Pascal', '3 r Hastings', '15000', 'AURRILLAC', '290,75');
insert into practitioner values (57,2, 'Robert', 'Pascal', '31 r St Jean', '93000', 'BOBIGNY', '162,41');
insert into practitioner values (58,5, 'Jean', 'Pascale', '114 r Authie', '49100', 'SAUMUR', '375,52');
insert into practitioner values (59,3, 'Chanteloube', 'Patrice', '14 av Thiès', '13000', 'MARSEILLE', '478,01');
insert into practitioner values (60,4, 'Lecuirot', 'Patrice', 'résid St Pères 55 r Pigacière', '54000', 'NANCY', '239,66');
insert into practitioner values (61,1, 'Gandon', 'Patrick', '47 av Robert Schuman', '37000', 'TOURS', '599,06');
insert into practitioner values (62,2, 'Mirouf', 'Patrick', '22 r Puits Picard', '74000', 'ANNECY', '458,42');
insert into practitioner values (63,5, 'Boireaux', 'Philippe', '14 av Thiès', '10000', 'CHALON EN CHAMPAGNE', '454,48');
insert into practitioner values (64,3, 'Cendrier', 'Philippe', '7 pl St Gilles', '12000', 'RODEZ', '164,16');
insert into practitioner values (65,4, 'Duhamel', 'Philippe', '114 r Authie', '34000', 'MONTPELLIER', '98,62');
insert into practitioner values (66,1, 'Grigy', 'Philippe', '15 r Mélingue', '44000', 'CLISSON', '285,1');
insert into practitioner values (67,2, 'Linard', 'Philippe', '1 r Albert de Mun', '81000', 'ALBI', '486,3');
insert into practitioner values (68,5, 'Lozier', 'Philippe', '8 r Gaillon', '31000', 'TOULOUSE', '48,4');
insert into practitioner values (69,3, 'Dechâtre', 'Pierre', '63 av Thiès', '23000', 'MONTLUCON', '253,75');
insert into practitioner values (70,4, 'Goessens', 'Pierre', '22 r Jean Romain', '40000', 'MONT DE MARSAN', '426,19');
insert into practitioner values (71,1, 'Leménager', 'Pierre', '39 av 6 Juin', '57000', 'METZ', '118,7');
insert into practitioner values (72,2, 'Née', 'Pierre', '39 av 6 Juin', '82000', 'MONTAUBAN', '72,54');
insert into practitioner values (73,5, 'Guyot', 'Pierre-Laurent', '43 bd Gén Vanier', '48000', 'MENDE', '352,31');
insert into practitioner values (74,3, 'Chauchard', 'Roger', '9 r Vaucelles', '13000', 'MARSEILLE', '552,19');
insert into practitioner values (75,4, 'Mabire', 'Roland', '11 r Boutiques', '67000', 'STRASBOURG', '422,39');
insert into practitioner values (76,1, 'Leroy', 'Soazig', '45 r Boutiques', '61000', 'ALENCON', '570,67');
insert into practitioner values (77,2, 'Guyot', 'Stéphane', '26 r Hérouville', '46000', 'FIGEAC', '28,85');
insert into practitioner values (78,5, 'Delposen', 'Sylvain', '39 av 6 Juin', '27000', 'DREUX', '292,01');
insert into practitioner values (79,3, 'Rault', 'Sylvie', '15 bd Richemond', '02000', 'SOISSON', '526,6');
insert into practitioner values (80,4, 'Renouf', 'Sylvie', '98 bd Mar Lyautey', '88000', 'EPINAL', '425,24');
insert into practitioner values (81,1, 'Alliet-Grach', 'Thierry', '14 av Thiès', '07000', 'PRIVAS', '451,31');
insert into practitioner values (82,2, 'Bayard', 'Thierry', '92 r Falaise', '42000', 'SAINT ETIENNE', '271,71');
insert into practitioner values (83,5, 'Gauchet', 'Thierry', '7 r Desmoueux', '38100', 'GRENOBLE', '406,1');
insert into practitioner values (84,3, 'Bobichon', 'Tristan', '219 r Caponière', '09000', 'FOIX', '218,36');
insert into practitioner values (85,4, 'Duchemin-Laniel', 'Véronique', '130 r St Jean', '33000', 'LIBOURNE', '265,61');
insert into practitioner values (86,1, 'Laurent', 'Younès', '34 r Demolombe', '53000', 'MAYENNE', '496,1');

insert into district values (1, 1, 'AL', 'Alsace Lorraine');
insert into district values (2, 5, 'AQ', 'Aquitaine');
insert into district values (3, 4, 'AU', 'Auvergne');
insert into district values (4, 3, 'BG', 'Bretagne');
insert into district values (5, 3, 'BN', 'Basse Normandie');
insert into district values (6, 1, 'BO', 'Bourgogne');
insert into district values (7, 2, 'CA', 'Champagne Ardennes');
insert into district values (8, 4, 'CE', 'Centre');
insert into district values (9, 1, 'FC', 'Franche Comté');
insert into district values (10,2, 'HN', 'Haute Normandie');
insert into district values (11,4, 'IF', 'Ile de France');
insert into district values (12,5, 'LG', 'Languedoc');
insert into district values (13,4, 'LI', 'Limousin');
insert into district values (14,5, 'MP', 'Midi Pyrénée');
insert into district values (15,2, 'NP', 'Nord Pas de Calais');
insert into district values (16,5, 'PA', 'Provence Alpes Cote d''Azur');
insert into district values (17,3, 'PC', 'Poitou Charente');
insert into district values (18,2, 'PI', 'Picardie');
insert into district values (19,3, 'PL', 'Pays de Loire');
insert into district values (20,1, 'RA', 'Rhone Alpes');
insert into district values (21,5, 'RO', 'Roussilon');
insert into district values (22,3, 'VD', 'Vendée');

insert into sector values (1, 'E','Est');
insert into sector values (2, 'N','Nord');
insert into sector values (3, 'O','Ouest');
insert into sector values (4, 'P','Paris centre');
insert into sector values (5, 'S','Sud');

insert into speciality values (1, 'ACP', 'anatomie et cytologie pathologiques');
insert into speciality values (2, 'AMV', 'angéiologie, médecine vasculaire');
insert into speciality values (3, 'ARC', 'anesthésiologie et réanimation chirurgicale');
insert into speciality values (4, 'BM', 'biologie médicale');
insert into speciality values (5, 'CAC', 'cardiologie et affections cardio-vasculaires');
insert into speciality values (6, 'CCT', 'chirurgie cardio-vasculaire et thoracique');
insert into speciality values (7, 'CG', 'chirurgie générale');
insert into speciality values (8, 'CMF', 'chirurgie maxillo-faciale');
insert into speciality values (9, 'COM', 'cancérologie, oncologie médicale');
insert into speciality values (10, 'COT', 'chirurgie orthopédique et traumatologie');
insert into speciality values (11, 'CPR', 'chirurgie plastique reconstructrice et esthétique');
insert into speciality values (12, 'CU', 'chirurgie urologique');
insert into speciality values (13, 'CV', 'chirurgie vasculaire');
insert into speciality values (14, 'DN', 'diabétologie-nutrition, nutrition');
insert into speciality values (15, 'DV', 'dermatologie et vénéréologie');
insert into speciality values (16, 'EM', 'endocrinologie et métabolismes');
insert into speciality values (17, 'ETD', 'évaluation et traitement de la douleur');
insert into speciality values (18, 'GEH', 'gastro-entérologie et hépatologie (appareil digestif)');
insert into speciality values (19, 'GMO', 'gynécologie médicale, obstétrique');
insert into speciality values (20, 'GO', 'gynécologie-obstétrique');
insert into speciality values (21, 'HEM', 'maladies du sang (hématologie)');
insert into speciality values (22, 'MBS', 'médecine et biologie du sport');
insert into speciality values (23, 'MDT', 'médecine du travail');
insert into speciality values (24, 'MMO', 'médecine manuelle - ostéopathie');
insert into speciality values (25, 'MN', 'médecine nucléaire');
insert into speciality values (26, 'MPR', 'médecine physique et de réadaptation');
insert into speciality values (27, 'MTR', 'médecine tropicale, pathologie infectieuse et tropicale');
insert into speciality values (28, 'NEP', 'néphrologie');
insert into speciality values (29, 'NRC', 'neurochirurgie');
insert into speciality values (30, 'NRL', 'neurologie');
insert into speciality values (31, 'ODM', 'orthopédie dento maxillo-faciale');
insert into speciality values (32, 'OPH', 'ophtalmologie');
insert into speciality values (33, 'ORL', 'oto-rhino-laryngologie');
insert into speciality values (34, 'PEA', 'psychiatrie de l''enfant et de l''adolescent');
insert into speciality values (35, 'PME', 'pédiatrie maladies des enfants');
insert into speciality values (36, 'PNM', 'pneumologie');
insert into speciality values (37, 'PSC', 'psychiatrie');
insert into speciality values (38, 'RAD', 'radiologie (radiodiagnostic et imagerie médicale)');
insert into speciality values (39, 'RDT', 'radiothérapie (oncologie option radiothérapie)');
insert into speciality values (40, 'RGM', 'reproduction et gynécologie médicale');
insert into speciality values (41, 'RHU', 'rhumatologie');
insert into speciality values (42, 'STO', 'stomatologie');
insert into speciality values (43, 'SXL', 'sexologie');
insert into speciality values (44, 'TXA', 'toxicomanie et alcoologie');

insert into working values (1, '1992-12-11',5, 'Visiteur');
insert into working values (1, '1996-05-27',4, 'Visiteur');
insert into working values (2, '1991-08-26',20, 'Visiteur');
insert into working values (2, '1997-09-19',20, 'Délégué');
insert into working values (3, '1987-07-17',14, 'Visiteur');
insert into working values (3, '1995-05-19',21, 'Visiteur');
insert into working values (3, '1999-08-21',21, 'Délégué');
insert into working values (4, '1999-01-02',17, 'Visiteur');
insert into working values (5, '1996-03-11',1, 'Visiteur');
insert into working values (6, '1997-03-21',4, 'Visiteur');
insert into working values (7, '1999-01-31',19, 'Visiteur');
insert into working values (8, '1994-07-03',19, 'Visiteur');
insert into working values (8, '2000-01-01',19, 'Délégué');
insert into working values (9, '2000-08-02',12, 'Visiteur');
insert into working values (10, '1993-12-06',8, 'Délégué');
insert into working values (10, '1999-06-18',8, 'Responsable');
insert into working values (11, '1997-09-25',2, 'Visiteur');
insert into working values (12, '1998-01-18',16, 'Visiteur');
insert into working values (13, '1995-10-21',20, 'Visiteur');
insert into working values (14, '1989-02-01',16, 'Visiteur');
insert into working values (14, '1997-02-01',16, 'Délégué');
insert into working values (14, '2001-03-03',16, 'Responsable');
insert into working values (15, '1992-05-05',7, 'Visiteur');
insert into working values (16, '1991-04-09',1, 'Visiteur');
insert into working values (17, '1991-12-05',19, 'Visiteur');
insert into working values (18, '1997-11-18',9, 'Délégué');
insert into working values (18, '2002-03-20',9, 'Responsable');
insert into working values (19, '1989-03-24',1, 'Visiteur');
insert into working values (20, '1993-05-17',1, 'Délégué');
insert into working values (20, '2000-02-29',1, 'Responsable');
insert into working values (21, '1988-04-26',11, 'Visiteur');
insert into working values (22, '1996-02-19',14, 'Visiteur');
insert into working values (23, '1990-11-27',14, 'Visiteur');
insert into working values (23, '1995-11-27',14, 'Délégué');
insert into working values (23, '2000-11-27',2, 'Responsable');
insert into working values (24, '1991-10-31',10, 'Visiteur');
insert into working values (25, '1993-06-08',20, 'Visiteur');
insert into working values (26, '1997-02-15',20, 'Visiteur');
insert into working values (27, '1994-05-03',14, 'Visiteur');
insert into working values (28, '1996-01-18',11, 'Visiteur');
insert into working values (29, '1999-03-27',18, 'Délégué');
insert into working values (29, '2000-10-31',18, 'Responsable');
insert into working values (30, '1985-10-02',4, 'Visiteur');
insert into working values (31, '1996-01-13',13, 'Visiteur');
insert into working values (32, '1993-05-08',13, 'Visiteur');
insert into working values (33, '1998-04-26',11, 'Visiteur');
insert into working values (34, '1993-08-26',3, 'Visiteur');
insert into working values (35, '1992-11-01',7, 'Visiteur');
insert into working values (36, '1998-02-25',7, 'Responsable');
insert into working values (37, '1992-12-16',15, 'Visiteur');
insert into working values (38, '1998-06-18',11, 'Responsable');
insert into working values (39, '1996-11-21',12, 'Visiteur');
insert into working values (40, '1983-03-23',7, 'Visiteur');
insert into working values (40, '1992-04-03',1, 'Délégué');
insert into working values (41, '1995-02-02',19, 'Visiteur');
insert into working values (42, '1995-06-05',17, 'Visiteur');
insert into working values (43, '1997-01-24',19, 'Visiteur');
insert into working values (44, '1996-02-27',9, 'Visiteur');
insert into working values (45, '1987-10-06',14, 'Visiteur');
insert into working values (46, '1990-10-13',1, 'Visiteur');
insert into working values (46, '1999-04-08',1, 'Délégué');
insert into working values (47, '1996-03-06',10, 'Visiteur');
insert into working values (48, '1992-08-30',8, 'Visiteur');
insert into working values (49, '1994-12-19',18, 'Visiteur');
insert into working values (50, '1995-01-05',12, 'Visiteur');
insert into working values (51, '1992-12-24',11, 'Visiteur');
insert into working values (52, '1992-12-14',5, 'Délégué');
insert into working values (52, '1999-07-17',5, 'Responsable');
insert into working values (53, '1998-07-27',17, 'Visiteur');
insert into working values (54, '1994-12-12',18, 'Visiteur');
insert into working values (55, '1977-10-03',8, 'Visiteur');
insert into working values (56, '1997-03-30',2, 'Visiteur');
insert into working values (57, '1990-03-01',21, 'Visiteur');
insert into working values (58, '1991-06-23',6, 'Visiteur');
insert into working values (59, '1997-09-06',5, 'Visiteur');
insert into working values (60, '1984-07-29',5, 'Visiteur');
insert into working values (60, '1998-05-25',5, 'Responsable');
insert into working values (61, '1990-06-30',4, 'Visiteur');
insert into working values (62, '1995-11-14',9, 'Visiteur');
insert into working values (63, '1992-09-25',13, 'Visiteur');
insert into working values (64, '1995-03-09',6, 'Visiteur');
insert into working values (65, '1997-08-29',18, 'Visiteur');
insert into working values (66, '1994-11-29',14, 'Visiteur');
insert into working values (67, '1991-03-29',8, 'Visiteur');

insert into practitioner_type values (1, 'MH', 'Médecin Hospitalier', 'Hopital ou clinique');
insert into practitioner_type values (2, 'MV', 'Médecine de Ville', 'Cabinet');
insert into practitioner_type values (3, 'PH', 'Pharmacien Hospitalier', 'Hopital ou clinique');
insert into practitioner_type values (4, 'PO', 'Pharmacien Officine', 'Pharmacie');
insert into practitioner_type values (5, 'PS', 'Personnel de santé', 'Centre paramédical');

insert into presentation  values (1, 'GE', 'Gélule');
insert into presentation  values (2, 'CE', 'Comprimé enrobé');
insert into presentation  values (3, 'CP', 'Comprimé pelliculé');
insert into presentation  values (4, 'CS', 'Comprimé à sucer');
insert into presentation  values (5, 'CF', 'Comprimé effervescent');
insert into presentation  values (6, 'CP', 'Comprimé pelliculé');
insert into presentation  values (7, 'CC', 'Comprimé à croquer');
insert into presentation  values (8, 'CG', 'Comprimé gastro-résistant');
insert into presentation  values (9, 'SI', 'Sirop');
insert into presentation  values (10, 'SU', 'Suppositoire');
insert into presentation  values (11, 'GR', 'Granulé');
insert into presentation  values (12, 'CO', 'Collutoire');
insert into presentation  values (13, 'GO', 'Gouttes');
insert into presentation  values (14, 'SA', 'Sachet');

insert into formulating values (1,1);
insert into formulating values (2,2);
insert into formulating values (3,3);
insert into formulating values (4,4);
insert into formulating values (5,5);
insert into formulating values (6,6);
insert into formulating values (7,7);
insert into formulating values (8,8);
insert into formulating values (9,9);
insert into formulating values (10,10);
insert into formulating values (11,11);
insert into formulating values (12,12);
insert into formulating values (13,13);
insert into formulating values (14,14);
insert into formulating values (15,1);
insert into formulating values (16,2);
insert into formulating values (17,3);
insert into formulating values (18,4);
insert into formulating values (19,5);
insert into formulating values (20,6);
insert into formulating values (21,7);
insert into formulating values (22,8);
insert into formulating values (23,9);
insert into formulating values (24,10);
insert into formulating values (25,11);
insert into formulating values (26,12);
insert into formulating values (27,13);
insert into formulating values (28,14);
insert into formulating values (1,7);
insert into formulating values (2,8);
insert into formulating values (3,9);
insert into formulating values (4,10);
insert into formulating values (5,11);
insert into formulating values (6,12);
insert into formulating values (7,13);
insert into formulating values (8,14);
insert into formulating values (9,1);
insert into formulating values (10,2);
insert into formulating values (11,3);
insert into formulating values (12,4);
insert into formulating values (13,5);
insert into formulating values (14,6);
insert into formulating values (15,7);
insert into formulating values (16,8);
insert into formulating values (17,9);
insert into formulating values (18,10);
insert into formulating values (19,11);
insert into formulating values (20,12);
insert into formulating values (21,13);
insert into formulating values (22,14);
insert into formulating values (23,3);
insert into formulating values (24,4);
insert into formulating values (25,5);
insert into formulating values (26,6);
insert into formulating values (27,7);
insert into formulating values (28,8);

